# Generated by Django 5.2.8 on 2025-11-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_bid', models.IntegerField()),
                ('aggressiveness', models.IntegerField(default=5)),
                ('min_delay', models.FloatField(default=1.0)),
                ('max_delay', models.FloatField(default=5.0)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='bots',
            field=models.ManyToManyField(blank=True, to='auctions.auctionbot'),
        ),
    ]
